# Generated by Django 5.2.17 on 2026-08-31 01:46

import contratistas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_perfilusuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclaracionMetodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "planta_area",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="planta / área"
                    ),
                ),
                (
                    "numero_pedido",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="número de pedido"
                    ),
                ),
                ("gerente_proyecto", models.CharField(blank=True, max_length=150)),
                ("contacto_nombre", models.CharField(blank=True, max_length=150)),
                ("contacto_telefono", models.CharField(blank=True, max_length=30)),
                ("fecha_elaboracion", models.DateField()),
                ("duracion_dias", models.PositiveIntegerField(default=1)),
                ("descripcion_trabajo", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("enviada", "Enviada"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("actualizada_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "declaración de método",
                "verbose_name_plural": "declaraciones de método",
                "ordering": ["-creada_en"],
            },
        ),
        migrations.CreateModel(
            name="ActividadMetodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("secuencia", models.TextField(verbose_name="secuencia de actividad")),
                (
                    "tecnicas_herramientas",
                    models.TextField(
                        blank=True, verbose_name="técnicas / herramientas / equipos"
                    ),
                ),
                ("descripcion_riesgo", models.TextField(blank=True)),
                (
                    "probabilidad_sin",
                    models.FloatField(
                        default=0, verbose_name="probabilidad (sin mitigación)"
                    ),
                ),
                (
                    "frecuencia_sin",
                    models.FloatField(
                        default=0, verbose_name="frecuencia (sin mitigación)"
                    ),
                ),
                (
                    "impacto_sin",
                    models.FloatField(
                        default=0, verbose_name="impacto (sin mitigación)"
                    ),
                ),
                ("medidas_mitigacion", models.TextField(blank=True)),
                (
                    "probabilidad_con",
                    models.FloatField(
                        default=0, verbose_name="probabilidad (con mitigación)"
                    ),
                ),
                (
                    "frecuencia_con",
                    models.FloatField(
                        default=0, verbose_name="frecuencia (con mitigación)"
                    ),
                ),
                (
                    "impacto_con",
                    models.FloatField(
                        default=0, verbose_name="impacto (con mitigación)"
                    ),
                ),
                ("permisos_requeridos", models.JSONField(blank=True, default=list)),
                (
                    "tarea_sif",
                    models.BooleanField(default=False, verbose_name="tarea SIF"),
                ),
                (
                    "declaracion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="contratistas.declaracionmetodo",
                    ),
                ),
            ],
            options={
                "verbose_name": "actividad de declaración de método",
                "verbose_name_plural": "actividades de declaración de método",
                "ordering": ["declaracion", "orden"],
            },
        ),
        migrations.CreateModel(
            name="EmpresaContratista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "nit",
                    models.CharField(blank=True, max_length=30, verbose_name="NIT"),
                ),
                (
                    "contacto_nombre",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="nombre de contacto"
                    ),
                ),
                (
                    "contacto_telefono",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="teléfono de contacto"
                    ),
                ),
                (
                    "contacto_correo",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo de contacto"
                    ),
                ),
                (
                    "responsable_sst_nombre",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="responsable SST/SISO"
                    ),
                ),
                (
                    "responsable_sst_telefono",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="teléfono responsable SST",
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratistas",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "empresa contratista",
                "verbose_name_plural": "empresas contratistas",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="declaracionmetodo",
            name="contratista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="declaraciones_metodo",
                to="contratistas.empresacontratista",
            ),
        ),
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=150)),
                ("apellidos", models.CharField(max_length=150)),
                (
                    "documento",
                    models.CharField(
                        max_length=30, verbose_name="documento de identidad"
                    ),
                ),
                (
                    "eps",
                    models.CharField(blank=True, max_length=100, verbose_name="EPS"),
                ),
                (
                    "arl",
                    models.CharField(blank=True, max_length=100, verbose_name="ARL"),
                ),
                (
                    "afp",
                    models.CharField(blank=True, max_length=100, verbose_name="AFP"),
                ),
                (
                    "tipo_vinculacion",
                    models.CharField(
                        choices=[("fijo", "Fijo"), ("temporal", "Temporal")],
                        default="fijo",
                        max_length=20,
                    ),
                ),
                ("fecha_inicio_contrato", models.DateField(blank=True, null=True)),
                (
                    "cursos_safety_academy",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Mapa {tipo_curso: fecha ISO o null} — ver Trabajador.CURSOS para las claves válidas",
                        verbose_name="cursos Safety Academy",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "contratista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trabajadores",
                        to="contratistas.empresacontratista",
                    ),
                ),
            ],
            options={
                "verbose_name": "trabajador",
                "verbose_name_plural": "trabajadores",
                "ordering": ["apellidos", "nombres"],
                "unique_together": {("contratista", "documento")},
            },
        ),
        migrations.CreateModel(
            name="RadicacionSeguridadSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveIntegerField()),
                ("mes", models.CharField(max_length=20)),
                (
                    "numero_planilla",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="número de planilla"
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="fecha de vencimiento de la planilla",
                    ),
                ),
                (
                    "soporte_pago",
                    models.FileField(
                        blank=True,
                        help_text="PDF de la planilla integrada de autoliquidación de aportes (PILA)",
                        null=True,
                        upload_to=contratistas.models.soporte_pago_upload_to,
                        verbose_name="soporte de pago",
                    ),
                ),
                ("interventor", models.CharField(blank=True, max_length=150)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("radicada_en", models.DateTimeField(auto_now_add=True)),
                ("revisada_en", models.DateTimeField(blank=True, null=True)),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radicaciones",
                        to="contratistas.trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "radicación de seguridad social",
                "verbose_name_plural": "radicaciones de seguridad social",
                "ordering": ["-radicada_en"],
            },
        ),
        migrations.CreateModel(
            name="FirmaMetodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            (
                                "supervisor_contratista",
                                "Supervisor de Seguridad del Contratista",
                            ),
                            ("delegado_abi", "Delegado (Contratante)"),
                            ("seguridad_planta", "Seguridad de Planta (Site)"),
                            ("lider_area", "Líder de Área"),
                            ("dueno_territorio", "Dueño de Territorio"),
                        ],
                        max_length=30,
                    ),
                ),
                ("nombre_firmante", models.CharField(max_length=150)),
                ("firmado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "declaracion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firmas",
                        to="contratistas.declaracionmetodo",
                    ),
                ),
            ],
            options={
                "verbose_name": "firma de declaración de método",
                "verbose_name_plural": "firmas de declaración de método",
                "ordering": ["declaracion", "rol"],
                "unique_together": {("declaracion", "rol")},
            },
        ),
    ]
