# Generated by Django 5.2.17 on 2026-08-31 02:15

import contratistas.models
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="radicacionseguridadsocial",
            name="soporte_pago",
            field=models.FileField(
                blank=True,
                help_text="PDF de la planilla integrada de autoliquidación de aportes (PILA)",
                null=True,
                upload_to=contratistas.models.soporte_pago_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    ),
                    core.validators.validar_tamano_archivo,
                ],
                verbose_name="soporte de pago",
            ),
        ),
    ]
