# Generated by Django 5.2.17 on 2026-08-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0002_alter_radicacionseguridadsocial_soporte_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajador",
            name="autorizacion_datos",
            field=models.BooleanField(
                default=False,
                help_text="Habeas Data (Ley 1581 de 2012) — el trabajador (o quien radica en su nombre) autorizó el tratamiento de sus datos personales, incluidos los de afiliación a seguridad social.",
                verbose_name="autorización de tratamiento de datos personales",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="autorizacion_datos_en",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="autorización otorgada el"
            ),
        ),
    ]
