# Generated by Django 5.2.17 on 2026-08-31 15:13

import contratistas.models
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0003_trabajador_autorizacion_datos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajador",
            name="soporte_autorizacion_datos",
            field=models.FileField(
                blank=True,
                help_text="Foto o PDF del formato de autorización firmado por el trabajador — respalda la casilla marcada arriba. Opcional pero recomendado como evidencia.",
                null=True,
                upload_to=contratistas.models.soporte_autorizacion_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    ),
                    core.validators.validar_tamano_archivo,
                ],
                verbose_name="evidencia de la autorización",
            ),
        ),
    ]
