# Generated by Django 5.2.17 on 2026-08-31 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0004_trabajador_soporte_autorizacion_datos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="firmametodo",
            name="firmante_usuario",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta autenticada que ejecutó la firma — no se puede eliminar mientras tenga firmas registradas. Nulo solo en firmas anteriores a este control.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="firmas_metodo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="firmametodo",
            name="hash_documento",
            field=models.CharField(
                blank=True,
                help_text="Huella sha256 de la declaración en el momento de esta firma.",
                max_length=64,
            ),
        ),
    ]
