# Generated by Django 5.2.17 on 2026-08-31 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0005_firmametodo_firmante_usuario_and_more"),
        ("core", "0002_perfilusuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("cargo", models.CharField(blank=True, max_length=150)),
                (
                    "rol_firma",
                    models.CharField(
                        choices=[
                            ("delegado_abi", "Delegado (Contratante)"),
                            ("seguridad_planta", "Seguridad de Planta (Site)"),
                            ("lider_area", "Líder de Área"),
                            ("dueno_territorio", "Dueño de Territorio"),
                        ],
                        max_length=30,
                    ),
                ),
                ("correo", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funcionarios",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "funcionario firmante",
                "verbose_name_plural": "funcionarios firmantes",
                "ordering": ["rol_firma", "nombre"],
            },
        ),
    ]
