# Generated by Django 5.2.17 on 2026-08-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0006_funcionario"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionAlertas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dias_alerta_vencimiento",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="A cuántos días de vencer una planilla se considera 'por vencer' en los indicadores.",
                        verbose_name="días de alerta antes de vencer",
                    ),
                ),
                (
                    "actualizada_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizada en"),
                ),
            ],
            options={
                "verbose_name": "configuración de alertas",
                "verbose_name_plural": "configuración de alertas",
            },
        ),
        migrations.CreateModel(
            name="CursoSafetyAcademy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.SlugField(unique=True)),
                ("etiqueta", models.CharField(max_length=150)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "curso Safety Academy",
                "verbose_name_plural": "cursos Safety Academy",
                "ordering": ["orden", "etiqueta"],
            },
        ),
        migrations.CreateModel(
            name="PermisoTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "permiso de trabajo",
                "verbose_name_plural": "permisos de trabajo",
                "ordering": ["orden", "nombre"],
            },
        ),
    ]
