# Generated by Django 5.2.17 on 2026-08-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0008_sembrar_cursos_y_permisos"),
    ]

    operations = [
        migrations.AddField(
            model_name="cursosafetyacademy",
            name="obligatorio",
            field=models.BooleanField(
                default=False,
                help_text="Si está marcado, se avisa cuando un trabajador activo no lo tiene completado.",
                verbose_name="obligatorio para todo trabajador",
            ),
        ),
    ]
