# Generated by Django 5.2.17 on 2026-08-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0009_cursosafetyacademy_obligatorio"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionalertas",
            name="correo_revisor",
            field=models.EmailField(
                blank=True,
                help_text="A dónde avisar cuando se radica seguridad social o se envía una declaración de método que queda pendiente de revisión. Vacío = no se envía ese aviso (el de aprobado/rechazado sigue yendo siempre al contacto de la empresa contratista).",
                max_length=254,
                verbose_name="correo para avisos de revisión pendiente",
            ),
        ),
    ]
