# Generated by Django 5.2.17 on 2026-08-31 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0010_configuracionalertas_correo_revisor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.CharField(max_length=100)),
                ("objeto_id", models.PositiveIntegerField()),
                ("objeto_str", models.CharField(max_length=300)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("creado", "Creado"),
                            ("actualizado", "Actualizado"),
                            ("eliminado", "Eliminado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cambios", models.JSONField(blank=True, default=dict)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoría",
                "verbose_name_plural": "registros de auditoría",
                "ordering": ["-fecha"],
            },
        ),
    ]
