# Generated by Django 5.2.17 on 2026-08-31 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0011_registroauditoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutorizacionIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="vigencia — desde")),
                ("fecha_fin", models.DateField(verbose_name="vigencia — hasta")),
                (
                    "hora_inicio",
                    models.TimeField(
                        blank=True, null=True, verbose_name="horario — desde"
                    ),
                ),
                (
                    "hora_fin",
                    models.TimeField(
                        blank=True, null=True, verbose_name="horario — hasta"
                    ),
                ),
                ("area_trabajo", models.CharField(max_length=200)),
                (
                    "sitio_encuentro_emergencia",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="sitio de encuentro en caso de emergencia",
                    ),
                ),
                (
                    "responsable_siso_nombre",
                    models.CharField(
                        max_length=150, verbose_name="responsable SISO del grupo"
                    ),
                ),
                (
                    "responsable_siso_telefono",
                    models.CharField(blank=True, max_length=30),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("enviada", "Enviada"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("actualizada_en", models.DateTimeField(auto_now=True)),
                (
                    "contratista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autorizaciones_ingreso",
                        to="contratistas.empresacontratista",
                    ),
                ),
                (
                    "declaracion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Declaración de método a la que corresponde este trabajo, si aplica.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autorizaciones_ingreso",
                        to="contratistas.declaracionmetodo",
                    ),
                ),
            ],
            options={
                "verbose_name": "autorización de ingreso",
                "verbose_name_plural": "autorizaciones de ingreso",
                "ordering": ["-creada_en"],
            },
        ),
        migrations.CreateModel(
            name="TrabajadorAutorizacionIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incluido", models.BooleanField(default=True)),
                ("motivo_exclusion", models.CharField(blank=True, max_length=300)),
                (
                    "autorizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trabajadores",
                        to="contratistas.autorizacioningreso",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autorizaciones_ingreso",
                        to="contratistas.trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "trabajador en autorización de ingreso",
                "verbose_name_plural": "trabajadores en autorización de ingreso",
                "ordering": ["-incluido", "trabajador__apellidos"],
                "unique_together": {("autorizacion", "trabajador")},
            },
        ),
    ]
