# Generated by Django 5.2.17 on 2026-08-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0012_autorizacioningreso_trabajadorautorizacioningreso"),
    ]

    operations = [
        migrations.AddField(
            model_name="autorizacioningreso",
            name="responsable_siso_cargo",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="cargo del responsable SISO"
            ),
        ),
    ]
