# Generated by Django 5.2.17 on 2026-09-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0013_autorizacioningreso_responsable_siso_cargo"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificacionInterna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            (
                                "declaracion_pendiente",
                                "Declaración pendiente de revisión",
                            ),
                            (
                                "declaracion_subsanada",
                                "Declaración corregida y reenviada",
                            ),
                            (
                                "radicacion_pendiente",
                                "Radicación pendiente de revisión",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                ("mensaje", models.CharField(max_length=255)),
                ("modelo", models.CharField(max_length=50)),
                ("objeto_id", models.PositiveIntegerField()),
                ("leida", models.BooleanField(default=False)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "notificación interna",
                "verbose_name_plural": "notificaciones internas",
                "ordering": ["-creada_en"],
            },
        ),
    ]
