# Generated by Django 5.2.17 on 2026-09-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0014_notificacioninterna"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipoProteccionPersonal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "equipo de protección personal",
                "verbose_name_plural": "equipos de protección personal",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="actividadmetodo",
            name="epp_requerido",
            field=models.JSONField(
                blank=True, default=list, verbose_name="EPP requerido"
            ),
        ),
    ]
