# Generated by Django 5.2.17 on 2026-09-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0016_sembrar_epp"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividadmetodo",
            name="altura_trabajo_metros",
            field=models.FloatField(
                blank=True,
                help_text="Opcional — si se diligencia, habilita alertas automáticas por los umbrales de las SOP de trabajo en altura (1.8 m, 4 m).",
                null=True,
                verbose_name="altura de trabajo (m)",
            ),
        ),
        migrations.AddField(
            model_name="actividadmetodo",
            name="profundidad_excavacion_metros",
            field=models.FloatField(
                blank=True,
                help_text="Opcional — si se diligencia, habilita alertas automáticas por los umbrales del SOP de excavaciones (1.2 m, 1.3 m, 5 m).",
                null=True,
                verbose_name="profundidad de excavación (m)",
            ),
        ),
    ]
