# Generated by Django 5.2.17 on 2026-09-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0017_actividadmetodo_altura_trabajo_metros_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajador",
            name="fecha_vencimiento_certificacion_alturas",
            field=models.DateField(
                blank=True,
                help_text="Opcional — solo si el trabajador hace trabajo en altura (el SOP exige recertificación cada 2 años).",
                null=True,
                verbose_name="vencimiento certificación de trabajo en alturas",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="fecha_vencimiento_examen_medico",
            field=models.DateField(
                blank=True,
                help_text="Opcional — solo si el trabajador hace trabajo en altura (el SOP exige examen vigente hace menos de 1 año).",
                null=True,
                verbose_name="vencimiento examen médico ocupacional",
            ),
        ),
    ]
