# Generated by Django 5.2.17 on 2026-09-01 15:23

import contratistas.models
import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contratistas",
            "0018_trabajador_fecha_vencimiento_certificacion_alturas_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="declaracionmetodo",
            name="archivo_origen_excel",
            field=models.FileField(
                blank=True,
                help_text="Libro de Excel que se subió para importar esta declaración — se conserva para que quien revisa pueda abrirlo y compararlo contra lo que quedó cargado.",
                null=True,
                upload_to=contratistas.models.declaracion_origen_excel_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["xlsx"]
                    ),
                    core.validators.validar_tamano_archivo,
                ],
                verbose_name="Excel original",
            ),
        ),
        migrations.CreateModel(
            name="NotaAlerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_alerta", models.CharField(max_length=60)),
                ("actividad_orden", models.PositiveIntegerField()),
                ("autor_nombre", models.CharField(blank=True, max_length=150)),
                ("texto", models.TextField()),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "declaracion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_alertas",
                        to="contratistas.declaracionmetodo",
                    ),
                ),
            ],
            options={
                "verbose_name": "nota de alerta",
                "verbose_name_plural": "notas de alertas",
                "ordering": ["creada_en"],
            },
        ),
    ]
