# Generated by Django 5.2.17 on 2026-09-01 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0019_declaracionmetodo_archivo_origen_excel_notaalerta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionCapacitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo_curso",
                    models.CharField(default="Inducción SST", max_length=150),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Video alojado externamente (ej. Cloudinary) — se reproduce directo desde ahí.",
                        max_length=500,
                        verbose_name="URL del video de inducción",
                    ),
                ),
                (
                    "puntaje_minimo_aprobacion",
                    models.PositiveIntegerField(
                        default=80, verbose_name="puntaje mínimo para aprobar (%)"
                    ),
                ),
                (
                    "actualizada_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizada en"),
                ),
            ],
            options={
                "verbose_name": "configuración de capacitación",
                "verbose_name_plural": "configuración de capacitación",
            },
        ),
        migrations.CreateModel(
            name="PreguntaCapacitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField(verbose_name="pregunta")),
                (
                    "opciones",
                    models.JSONField(
                        default=list,
                        help_text="Lista de textos de opción, en el orden a mostrar.",
                    ),
                ),
                (
                    "respuesta_correcta",
                    models.PositiveIntegerField(
                        verbose_name="índice de la opción correcta"
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "pregunta de capacitación",
                "verbose_name_plural": "preguntas de capacitación",
                "ordering": ["orden", "id"],
            },
        ),
        migrations.AddField(
            model_name="empresacontratista",
            name="capacitacion_habilitada_manual",
            field=models.BooleanField(
                default=False,
                help_text="La inducción previa a ingreso normalmente solo se habilita cuando esta empresa tiene una Declaración de Método aprobada. Marca esto para habilitarla de todas formas (ej. trabajos que no requieren declaración de método).",
                verbose_name="habilitar capacitación manualmente",
            ),
        ),
        migrations.CreateModel(
            name="RegistroCapacitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=200)),
                ("correo", models.EmailField(blank=True, max_length=254)),
                (
                    "documento",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="documento de identidad"
                    ),
                ),
                (
                    "respuestas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Índices de opción elegidos, en orden.",
                    ),
                ),
                ("calificacion", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_curso", "En curso"),
                            ("aprobado", "Aprobado"),
                            ("no_aprobado", "No aprobado"),
                        ],
                        default="en_curso",
                        max_length=20,
                    ),
                ),
                ("iniciado_en", models.DateTimeField(auto_now_add=True)),
                ("finalizado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "contratista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_capacitacion",
                        to="contratistas.empresacontratista",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        blank=True,
                        help_text="Se vincula solo si el documento ingresado coincide con un trabajador ya radicado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_capacitacion",
                        to="contratistas.trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de capacitación",
                "verbose_name_plural": "registros de capacitación",
                "ordering": ["-iniciado_en"],
            },
        ),
    ]
