# Generated by Django 5.2.17 on 2026-09-01 20:01

from django.db import migrations

# Contenido inicial tal cual el "FDT Evalúa visitantes" en Apps Script que
# reemplaza este módulo — el cliente pidió reusarlo tal cual al arrancar;
# tanto el video como estas preguntas quedan editables después desde
# Sistema > Capacitación, sin tocar código.
VIDEO_URL = "https://res.cloudinary.com/j3hvomfk/video/upload/v1788070967/Video_de_acceso_de_visitantes_FDT_1.mp4"

PREGUNTAS = [
    {
        "texto": "1. ¿Cuál es el mensaje principal del video respecto a la seguridad?",
        "opciones": [
            "La seguridad depende únicamente del supervisor.",
            "La seguridad es un valor fundamental y forma parte de todas las actividades.",
            "La seguridad solo aplica en producción.",
            "La seguridad es responsabilidad del departamento de Seguridad.",
        ],
        "respuesta_correcta": 1,
    },
    {
        "texto": "2. ¿Cuál de los siguientes riesgos es considerado principal dentro de la planta?",
        "opciones": [
            "Quemaduras por exposición solar.",
            "Atrapamientos en maquinaria y equipos en movimiento.",
            "Picaduras de insectos.",
            "Ruido excesivo en áreas de oficinas.",
        ],
        "respuesta_correcta": 1,
    },
    {
        "texto": "3. ¿Qué debe hacer un peatón al llegar a un cruce peligroso señalizado con líneas blancas y rojas?",
        "opciones": [
            "Continuar caminando porque el peatón siempre tiene la prioridad.",
            "Correr para cruzar más rápido y no interrumpir el tráfico.",
            "Parar, mirar hacia ambos lados y cruzar solo cuando sea seguro.",
            "Esperar a que el operador del montacargas le haga una señal manual.",
        ],
        "respuesta_correcta": 2,
    },
    {
        "texto": "4. ¿Qué debe hacer un trabajador o visitante cuando circula por áreas donde operan vehículos o maquinaria?",
        "opciones": [
            "Caminar por cualquier área que esté despejada.",
            "Confiar en que el operador del montacargas lo verá.",
            "Permanecer atento al entorno y respetar las rutas peatonales.",
            "Utilizar el teléfono celular mientras camina para ahorrar tiempo.",
        ],
        "respuesta_correcta": 2,
    },
    {
        "texto": "5. ¿Qué indica el video sobre el uso de teléfonos celulares o dispositivos electrónicos?",
        "opciones": [
            "No deben utilizarse bajo ninguna circunstancia mientras la persona se encuentra caminando.",
            "Solo pueden utilizarse durante la jornada laboral en áreas de producción.",
            "Pueden utilizarse en cualquier momento si es una llamada de trabajo.",
            "Solo están prohibidos para los visitantes, el personal de planta sí puede usarlos.",
        ],
        "respuesta_correcta": 0,
    },
    {
        "texto": "6. ¿Qué color de camisa usan los brigadistas de emergencia en la planta?",
        "opciones": ["Azul.", "Roja.", "Verde.", "Naranja."],
        "respuesta_correcta": 1,
    },
    {
        "texto": "7. En caso de una evacuación, ¿qué debe hacer un visitante o contratista?",
        "opciones": [
            "Buscar la salida más cercana por cuenta propia rápidamente.",
            "Seguir la señalización y dirigirse al punto de encuentro acompañado por su guía o brigadista.",
            "Permanecer en el área de trabajo hasta recibir una llamada de autorización.",
            "Regresar a su vehículo inmediatamente y abandonar la planta.",
        ],
        "respuesta_correcta": 1,
    },
    {
        "texto": "8. ¿Qué significa un sonido continuo de alarma según el video de inducción?",
        "opciones": [
            "Aviso de inicio o cambio de turno.",
            "Existe una emergencia real y deben seguirse los procedimientos de evacuación.",
            "Es el aviso de la hora de almuerzo.",
            "Indica que la jornada laboral ha finalizado.",
        ],
        "respuesta_correcta": 1,
    },
    {
        "texto": "9. ¿Por qué es importante mantenerse atento al entorno durante todo el recorrido por la planta?",
        "opciones": [
            "Para evitar incidentes con montacargas, maquinaria en movimiento u otros obstáculos.",
            "Para llegar más rápido al área de trabajo asignada.",
            "Únicamente para memorizar la ubicación de los baños y salidas.",
            "Para poder saludar a todos los compañeros durante el trayecto.",
        ],
        "respuesta_correcta": 0,
    },
    {
        "texto": "10. ¿Cuál es el objetivo final que transmite el video respecto a las personas en la planta?",
        "opciones": [
            "Que todas las personas regresen sanas y seguras a casa al finalizar su jornada.",
            "Cumplir estrictamente con los indicadores de producción sin importar el método.",
            "Finalizar los trabajos de mantenimiento lo más rápido posible.",
            "Mantener la planta limpia para evitar no conformidades en las auditorías.",
        ],
        "respuesta_correcta": 0,
    },
]


def sembrar(apps, schema_editor):
    ConfiguracionCapacitacion = apps.get_model("contratistas", "ConfiguracionCapacitacion")
    PreguntaCapacitacion = apps.get_model("contratistas", "PreguntaCapacitacion")

    ConfiguracionCapacitacion.objects.update_or_create(pk=1, defaults={"video_url": VIDEO_URL})

    if PreguntaCapacitacion.objects.exists():
        return
    for orden, datos in enumerate(PREGUNTAS):
        PreguntaCapacitacion.objects.create(
            texto=datos["texto"],
            opciones=datos["opciones"],
            respuesta_correcta=datos["respuesta_correcta"],
            orden=orden,
        )


def revertir(apps, schema_editor):
    ConfiguracionCapacitacion = apps.get_model("contratistas", "ConfiguracionCapacitacion")
    PreguntaCapacitacion = apps.get_model("contratistas", "PreguntaCapacitacion")
    PreguntaCapacitacion.objects.all().delete()
    ConfiguracionCapacitacion.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "contratistas",
            "0020_configuracioncapacitacion_preguntacapacitacion_and_more",
        ),
    ]

    operations = [migrations.RunPython(sembrar, revertir)]
