# Generated by Django 5.2.17 on 2026-09-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0023_restaurar_permisos_sin_equivalente_zbs"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividadmetodo",
            name="requiere_permiso_trabajo",
            field=models.BooleanField(
                default=False,
                help_text="El permiso de trabajo general (uno solo, distinto de los certificados de apoyo de la lista de abajo — LOTO, alturas, espacio confinado, etc.).",
                verbose_name="requiere permiso de trabajo general",
            ),
        ),
        migrations.AlterField(
            model_name="actividadmetodo",
            name="permisos_requeridos",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="certificados de apoyo requeridos",
            ),
        ),
    ]
