# Generated by Django 5.2.17 on 2026-09-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0025_renombrar_permisos_a_certificados_apoyo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permisotrabajo",
            options={
                "ordering": ["orden", "nombre"],
                "verbose_name": "certificado de apoyo",
                "verbose_name_plural": "certificados de apoyo",
            },
        ),
    ]
