# Generated by Django 5.2.17 on 2026-09-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0026_alter_permisotrabajo_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificacionEspecial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.SlugField(unique=True)),
                ("etiqueta", models.CharField(max_length=150)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "certificación especial",
                "verbose_name_plural": "certificaciones especiales",
                "ordering": ["orden", "etiqueta"],
            },
        ),
        migrations.AddField(
            model_name="trabajador",
            name="certificaciones_especiales",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Mapa {clave: fecha de vencimiento ISO o null} — ver CertificacionEspecial para las claves válidas. A diferencia de los cursos, solo se diligencia para quien realmente hace esa actividad (espacios confinados, conducción, manlift, grúa, soldador, rescatista, licencia SST, ...); no se avisa por las que un trabajador nunca necesitó.",
                verbose_name="certificaciones especiales",
            ),
        ),
    ]
