# Generated by Django 5.2.17 on 2026-09-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0028_sembrar_certificaciones_especiales"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificacionespecial",
            name="meses_vigencia",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Cada cuántos meses vence esta certificación (ej. 36 para espacios confinados). Déjalo vacío si no se conoce el período — al marcarla completada, el formulario sugiere hoy + estos meses como fecha de vencimiento, pero siempre queda editable a mano.",
                null=True,
                verbose_name="meses de vigencia",
            ),
        ),
        migrations.AddField(
            model_name="cursosafetyacademy",
            name="meses_vigencia",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Cada cuántos meses vence este curso (ej. 18). Déjalo vacío si no vence o no se conoce el período — al marcar el curso completado, el formulario sugiere hoy + estos meses como fecha de vencimiento, pero siempre queda editable a mano.",
                null=True,
                verbose_name="meses de vigencia",
            ),
        ),
        migrations.AlterField(
            model_name="cursosafetyacademy",
            name="obligatorio",
            field=models.BooleanField(
                default=False,
                help_text="Si está marcado, se avisa cuando un trabajador activo no lo tiene vigente.",
                verbose_name="obligatorio para todo trabajador",
            ),
        ),
        migrations.AlterField(
            model_name="trabajador",
            name="cursos_safety_academy",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Mapa {tipo_curso: fecha de vencimiento ISO o null} — ver CursoSafetyAcademy para las claves válidas. CursoSafetyAcademy.meses_vigencia (si está configurado) solo se usa para sugerir esta fecha al marcar el curso completado; el valor guardado siempre es la fecha de vencimiento real, editable libremente.",
                verbose_name="cursos Safety Academy",
            ),
        ),
    ]
