# Generated by Django 5.2.17 on 2026-09-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0030_sembrar_meses_vigencia_espacios_confinados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trabajador",
            name="fecha_vencimiento_certificacion_alturas",
            field=models.DateField(
                blank=True,
                help_text="Opcional — solo si el trabajador hace trabajo en altura (el SOP exige recertificación cada 18 meses).",
                null=True,
                verbose_name="vencimiento certificación de trabajo en alturas",
            ),
        ),
    ]
