# Generated by Django 5.2.17 on 2026-09-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contratistas",
            "0031_alter_trabajador_fecha_vencimiento_certificacion_alturas",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajador",
            name="fecha_revision_validacion",
            field=models.DateField(
                blank=True,
                help_text="Cuándo SST revisó/validó este registro — informativa, no afecta la vigencia de nada.",
                null=True,
                verbose_name="fecha de revisión y validación",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="numero_pedido_cm",
            field=models.CharField(
                blank=True,
                help_text="Campo libre del cliente — sin validación.",
                max_length=100,
                verbose_name="número de pedido o CM",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="tipo_validacion",
            field=models.CharField(
                blank=True,
                choices=[("ingreso", "Ingreso"), ("renovacion", "Renovación")],
                help_text="Si este registro es un ingreso nuevo o la renovación de uno existente — informativo.",
                max_length=20,
                verbose_name="validación",
            ),
        ),
    ]
