# Generated by Django 5.2.17 on 2026-09-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0032_trabajador_fecha_revision_validacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresacontratista",
            name="contrato_marco",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="contrato marco"
            ),
        ),
        migrations.AddField(
            model_name="empresacontratista",
            name="tipo_contratista",
            field=models.CharField(
                blank=True,
                help_text="Texto libre del cliente — sin lista fija.",
                max_length=100,
                verbose_name="tipo de contratista",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="area_trabajo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("proyecto", "Proyecto"),
                    ("envase", "Envase"),
                    ("elaboracion", "Elaboración"),
                    ("ingenieria_serv", "Ingeniería y Serv"),
                    ("calidad", "Calidad"),
                    ("people", "People"),
                ],
                max_length=30,
                verbose_name="área donde realiza la mayor parte de sus actividades",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="casco_rojo",
            field=models.BooleanField(
                default=False,
                help_text="Personal con casco rojo (nuevo ingreso/en inducción) según la convención del cliente.",
                verbose_name="¿actualmente es casco rojo?",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="clase_riesgo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "I"),
                    ("II", "II"),
                    ("III", "III"),
                    ("IV", "IV"),
                    ("V", "V"),
                ],
                help_text="Clase de riesgo ARL (I a V).",
                max_length=5,
                verbose_name="clase de riesgo",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="formato_inclusion_firmado",
            field=models.BooleanField(
                default=False,
                verbose_name="formato de inclusión firmado por todos los responsables",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="induccion_empleador_registrada",
            field=models.BooleanField(
                default=False,
                help_text="El registro de la inducción del empleador existe en el Drive/repositorio correspondiente.",
                verbose_name="inducción del empleador registrada",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="pago_seguridad_cumple",
            field=models.BooleanField(
                default=False,
                help_text="Verificación manual de que la radicación cumple con la fecha y la clase de riesgo de la actividad.",
                verbose_name="pago de seguridad social cumple",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="radicacion_ok",
            field=models.BooleanField(default=False, verbose_name="radicación OK"),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="radicado_por",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="radicado por"
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="registros_epp_entregados",
            field=models.BooleanField(
                default=False, verbose_name="registros de entrega de EPP y dotación"
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="requisitos_ok_verificados",
            field=models.BooleanField(
                default=False, verbose_name="requisitos OK verificados"
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="responsable_sst_planta_nombre",
            field=models.CharField(
                blank=True,
                help_text="Persona del cliente que hizo seguimiento a este registro.",
                max_length=150,
                verbose_name="responsable de SST en planta",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="responsable_sst_planta_telefono",
            field=models.CharField(
                blank=True,
                max_length=30,
                verbose_name="teléfono del responsable de SST en planta",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="validador",
            field=models.CharField(
                blank=True,
                help_text="Quién validó este registro — texto libre.",
                max_length=150,
                verbose_name="validador",
            ),
        ),
    ]
