# Generated by Django 5.2.17 on 2026-09-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0033_empresacontratista_contrato_marco_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresacontratista",
            name="es_visitantes",
            field=models.BooleanField(
                default=False,
                help_text="Marca la única fila usada para agrupar las inducciones de visitas externas y auditorías a planta (rol de usuario Visitante/Auditor, ver PerfilUsuario) — no es una empresa contratista real. Se crea sola la primera vez que hace falta, ver EmpresaContratista.obtener_visitantes().",
                verbose_name="es la empresa pseudo-contratista de visitantes",
            ),
        ),
    ]
