# Generated by Django 5.2.17 on 2026-09-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0034_empresacontratista_es_visitantes"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioncapacitacion",
            name="correos_porteria",
            field=models.TextField(
                blank=True,
                help_text='Direcciones (separadas por coma) a las que se manda el listado de aprobados — se actualiza sola cada vez que un Administrador usa "Enviar listado a portería", así queda precargada la próxima vez sin tener que volver a escribirla.',
                verbose_name="correos de portería",
            ),
        ),
    ]
