# Generated by Django 5.2.17 on 2026-09-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0035_configuracioncapacitacion_correos_porteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrocapacitacion",
            name="fecha_vencimiento",
            field=models.DateField(
                blank=True,
                help_text="Se calcula sola al aprobar — finalizado_en + CursoSafetyAcademy('induccion_sst').meses_vigencia (6 meses por defecto). Vacía si ese curso no tiene meses de vigencia configurados, o si el intento todavía no se aprobó.",
                null=True,
                verbose_name="vigente hasta",
            ),
        ),
    ]
