# Generated by Django 5.2.17 on 2026-08-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "nit",
                    models.CharField(blank=True, max_length=30, verbose_name="NIT"),
                ),
                ("direccion", models.CharField(blank=True, max_length=255)),
                (
                    "contacto_nombre",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="nombre de contacto"
                    ),
                ),
                (
                    "contacto_telefono",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="teléfono de contacto"
                    ),
                ),
                (
                    "contacto_correo",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo de contacto"
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "empresa",
                "verbose_name_plural": "empresas",
                "ordering": ["nombre"],
            },
        ),
    ]
