# Generated by Django 5.2.17 on 2026-08-31 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0013_autorizacioningreso_responsable_siso_cargo"),
        ("core", "0002_perfilusuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="contratista",
            field=models.ForeignKey(
                blank=True,
                help_text="Solo aplica para el rol Contratista: la empresa a la que representa este usuario en el portal — define qué datos puede ver y editar.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios_portal",
                to="contratistas.empresacontratista",
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("administrador", "Administrador"),
                    ("operador", "Operador"),
                    ("contratista", "Contratista"),
                ],
                default="operador",
                max_length=20,
            ),
        ),
    ]
