# Generated by Django 5.2.17 on 2026-09-17 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0034_empresacontratista_es_visitantes"),
        ("core", "0005_registroiniciosesion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilusuario",
            name="contratista",
            field=models.ForeignKey(
                blank=True,
                help_text="Para el rol Contratista: la empresa a la que representa este usuario en el portal. Para el rol Visitante/Auditor: se autoasigna a la empresa pseudo-contratista 'Visitas y Auditorías Externas' (ver EmpresaContratista.obtener_visitantes) — no se elige a mano.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios_portal",
                to="contratistas.empresacontratista",
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("administrador", "Administrador"),
                    ("operador", "Operador"),
                    ("contratista", "Contratista"),
                    ("visitante", "Visitante/Auditor"),
                ],
                default="operador",
                max_length=20,
            ),
        ),
    ]
