# Generated by Django 5.2.17 on 2026-09-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_backfill_contratista_visitante"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="visitante_password_generada_en",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="contraseña generada en"
            ),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="visitante_password_texto_plano",
            field=models.CharField(
                blank=True,
                help_text="Solo para el rol Visitante/Auditor — ver core.views.enviar_acceso_visitantes. Se guarda en texto plano (además del hash normal de la contraseña) para poder reenviarla igual a nuevos destinatarios mientras siga vigente (24 horas desde visitante_password_generada_en), sin invalidar de una la que ya recibieron otras visitas — es una cuenta compartida y de propósito único (solo el curso de Capacitación), pensada para distribuirse por correo.",
                max_length=64,
                verbose_name="contraseña vigente (texto plano)",
            ),
        ),
    ]
