"""Catálogo de peligros de referencia — copiado tal cual del formato real
de Declaración de Método del cliente (hoja "Catálogo de Peligros"), para
incluirlo como hoja de consulta en el Excel exportado. No es un catálogo
editable ni se usa para validar nada — es solo texto de referencia."""

# (tipo_peligro, materia_o_energia, tipo_materia_o_energia, peligro, tipo_de_peligro, riesgo)
CATALOGO_PELIGROS = [
    ('Físicos', 'Energía', 'Eléctrica ', 'Electricidad estática', 'Electricidad Estática y Atmosferica', ''),
    ('Físicos', 'Energía', 'Eléctrica ', 'Corriente eléctrica', 'Corriente Eléctrica', 'Contacto con corriente eléctrica (Electrocución)'),
    ('Físicos', 'Energía', 'Eléctrica ', 'Electricidad residual', 'Electricidad Residual', 'Contacto con corriente eléctrica residual (Electrocución)'),
    ('Físicos', 'Energía', 'Eléctrica ', 'Electricidad atmosférica', '', ''),
    ('Físicos', 'Energía', 'Mecánica ', 'Transmisiones Mecánica de fuerza', 'Transmisión de Fuerzas mecánicas, partes en movimiento,propulsado por  por cualquier tipo de energia (engranes, cadenas, bandas, piñones, pistones, etc.)', 'Atrapado por / golpeado por transmisiones de fuerza (Escoriaciones, Fracturas, Amputaciones)'),
    ('Físicos', 'Energía', 'Mecánica ', 'Transmisiones de fuerza residual', 'Mecánica Residual, ciclos de movimientos sin terminar propulsado por  por cualquier tipo de energia, en (engranes, cadenas, bandas, piñones, etc.)', 'Atrapado por / golpeado por transmisiones de fuerza (Escoriaciones, Fracturas, Amputaciones)'),
    ('Físicos', 'Energía', 'Hidráulica', 'Transmisión Hidráulica de fuerza', '', ''),
    ('Físicos', 'Energía', 'Hidráulica', 'Presión Hidráulica Contenida', 'Presión contenida, por fluidos (Tanques tuberías mangueras, etc.)', 'Contacto con presión contenida (Contución)'),
    ('Físicos', 'Energía', 'Hidráulica', 'Energía Hidráulica residual', '', ''),
    ('Físicos', 'Energía', 'Neumática', 'Transmisión Neumática de fuerza', '', ''),
    ('Físicos', 'Energía', 'Neumática', 'Energía Neumática residual', '', ''),
    ('Físicos', 'Energía', 'Neumática', 'Presión Neumática Contenida', 'Presión contenida, por fluidos (Tanques tuberías mangueras, etc.)', 'Contacto con presión contenida (Contución)'),
    ('Físicos', 'Energía', 'Neumática', 'Vacío', 'Vacío,  colapsar.', 'NA'),
    ('Físicos', 'Energía', 'Térmica', 'Superficies con temperatura mayor a 50°C', 'Superficies con Temperaturas Mayor a 50°C (hornos, muflas, etc.)', 'Contacto con Temperaturas Mayor a 50°C (Quemadura)'),
    ('Físicos', 'Energía', 'Térmica', 'Superficies con temperatura menor a - 18°C', 'Superficies con Temperaturas Menor a -18°C (criogenicas. Etc..)', 'Contacto con Temperaturas Menor a -18°C (Quemadura)'),
    ('Físicos', 'Energía', 'Potencial', 'Trabajos a desnivel mayor a 1,80 m', 'Trabajos en Altura (a Desnivel, mayor a 1.80 m)', 'Caida diferente nivel (Golpe contuso, fracturas, muerte)'),
    ('Físicos', 'Energía', 'Potencial', 'Manejo de materiales o herramientas (caída)', 'Caída de materiales o herramienta (caída de objetos)', 'Golpeado por herramienta (Golpes contusos, Fracturas)'),
    ('Físicos', 'Energía', 'Ionizante', 'Radiación ionizante', 'Radiación Ionizante( fuente radiactivo o rayos X)', 'Exposición a Radiaciones Ionizante (Quemadura)'),
    ('Físicos', 'Energía', 'No ionizantes', 'Radiación infrarroja', 'Radiación Infrarroja (soldaduras eléctrica y oxicorte)', 'Exposición a Radiaciones Infrarroja (Quemadura)'),
    ('Físicos', 'Energía', 'No ionizantes', 'Radiación ultravioleta', 'Radiación Ultravioleta (soldadura eléctrica, arcos eléctricos)', 'Exposición a Radiaciones Ultravioleta (Quemadura)'),
    ('Físicos', 'Energía', 'No ionizantes', 'Microondas', 'Microondas, (horno de secado de barniz y transmisión de comunicaciones)', 'NA'),
    ('Físicos', 'Energía', 'No ionizantes', 'Rayos láser', 'Rayos Láser (termómetros, señalizadores y equipo de laboratorio)', 'Exposición a Rayos laser (Quemadura)'),
    ('Físicos', 'Energía', 'Cinética', 'Cuerpos en movimiento', 'Vehiculos en  movimiento, (Autos, trailer, montacargas)', 'Atrapado por / golpeado por cuerpos en movimiento (Escoriaciones, fracturas, muerte)'),
    ('Físicos', 'Energía', 'Cinética', 'Desprendimiento de partículas', 'Desprendimiento de partículas por (esmeriles, material fundido de soldadura, corte y desbaste, y operaciones de limpieza con aire a presión.)', 'Exposición a partículas suspendidas (Herida)'),
    ('Físicos', 'Materia', 'Gaseosa', 'Deficiencia de oxígeno', 'Deficiencia de Oxigeno , (atmósfera con gases inertes)', 'Exposición a deficiencia de oxigeno (Asfixia)'),
    ('Físicos', 'Materia', 'Sólida ', 'Superficie resbalosa o irregulares', 'Superficies de Trabajo irregular, estrechas  obstruidas húmedas y resbalosas, (áreas de trabajo, pasillos escaleras, etc.)', 'Caida mismo nivel (Golpe contuso, Fracturas)'),
    ('Físicos', 'Materia', 'Sólida ', 'Cuerpos punzo-cortante', 'Cuerpos Punzocortantes (cutters, navajas, fleje, esqueleto, greña, lamina, vidrios, refacciones o piezas de equipos y maquinarias y agua a alta presión)', 'Contacto con cuerpos punzocortantes (Heridas cortantes)'),
    ('Físicos', 'Materia', 'Sólida ', 'Partículas suspendidas', 'Partículas Suspendidas (materiales orgánicos e inorgánicos, polvos, tierras, misting,)', 'Exposición a partículas suspendidas (Asfixia)'),
    ('Físicos', 'Materia', 'Sólida ', 'Materia (sólida o líquida) contenida en superficies abiertas', 'Superficies abiertas que contienen liquidos (tanques, cisternas, piletas y que pueden provocar el ahogamiento de personas, en caso de caída)', 'Atrapado por liquidos contenidos en superficies abiertas (Ahogamiento)'),
    ('Químicos', 'Energía', 'Química', 'Reacción exotérmica', '', ''),
    ('Químicos', 'Energía', 'Electroquímica', 'Corriente eléctrica', 'Corriente Eléctrica', 'Contacto con corriente eléctrica (Electrocución)'),
    ('Químicos', 'Materia', 'Sólida / Líquida / Gaseosa', 'Corrosividad', 'Corrosividad Causan destrucción y/o alteración a materiales y tejido vivo (ácido sulfúrico, sosa cáustica, etc.)', 'Contacto con materiales corrosivos (Quemadura)'),
    ('Químicos', 'Materia', 'Sólida / Líquida / Gaseosa', 'Reactividad', 'Reactividad e  Inestabilidad.   liberación de energía por sustancias o mezclas de sustancias  ejemplo: ácido sulfúrico con agua', 'Exposición a materiales toxicos (Intoxicación)'),
    ('Químicos', 'Materia', 'Sólida / Líquida / Gaseosa', 'Explosividad', 'Explosividad por incremento de temperatura o presión sobre su masa, reaccionando repentinamente, generando alta temperatura y presiones sobre el medio ambiente circundante.(atmósferas explosivas de  gases inflamables  mezclados en el aire, en espacios confinados', 'Exposición / Contacto a sobre presión (Golpe)'),
    ('Químicos', 'Materia', 'Sólida / Líquida / Gaseosa', 'Toxicidad', 'Toxicidad, capacidad de la sustancia de causar daño a la salud u organismo vivo (cloro, gases producto de la combustión.)', 'Exposición a materiales toxicos (Intoxicación)'),
    ('Químicos', 'Materia', 'Sólida / Líquida / Gaseosa', 'Inflamabilidad', 'Inflamabilidad/ Combustibles (materiales inflamables como:gas L.P. Solventes, acetileno gasolina, etc. Y Combustibles como: diesel, madera, papel, etc;)', 'Exposición / Contacto a Inflamabilidad (Quemadura)'),
    ('Químicos', 'Materia', 'Sólida / Líquida / Gaseosa', 'Combustible', 'Combustibles. Por materiales comunes fuego tipo "A" como madera, papel, plasticos.', 'Contacto o Exposición a fuego (Quemadura)'),
    ('Biológicos', 'N/A', 'N.A.', 'Microorganismos patógenos', 'Microorganismos Patógenos (virus, bacterias, parásitos, hongos, etc)', 'Contacto o Exposición a Micro organismos patogenos  (Enfermedad)'),
    ('Biológicos', 'N/A', 'N.A.', 'Fauna', 'Fauna (perros, alacranes, arañas, víboras, abejas, etc.)', 'Contacto o Exposición a fauna (Picadura, modrida)'),
    ('Biológicos', 'N/A', 'N.A.', 'Flora', 'Flora (ramas de árbol, troncos, plantas)', 'Contacto o Exposición a flora (Herida)'),
    ('Ergonómicos', 'Energía', 'Acústica', 'Intensidad de ruido mayor a 85 dB.', 'Intensidad de Ruido Mayor a 85 db. (no se puede conversar en una distancia de 2 a 3 mts.', 'Exposición a ruido mayor a 85 db (Sordera)'),
    ('Ergonómicos', 'Energía', 'Lumínica', 'Intensidad de luz', 'Intensidad de luz (deslumbra por intensidad, o impide la visión por ser deficiente)', 'Exposición a deficiencia de luz (Caida, golpe)'),
    ('Ergonómicos', 'Energía', 'Mecánica ', 'Vibraciones', '', ''),
    ('Ergonómicos', 'Energía', 'Mecánica ', 'Fuentes que generen que la temperatura corporal sea inferior a 36°C', 'Fuentes que generen que la temperatura corporal se reduzca a menos de  36° C (Congeladores)', 'Exposición a frio (Enfermedad)'),
    ('Ergonómicos', 'Energía', 'Térmica', 'Fuentes que generen que la temperatura corporal sea mayor a 38°C.', 'Fuentes que generen que la temperatura corporal aumente a más de 38° C (fundidoras, hornos que provocan sudor intenso, o deshidratación)', 'Exposición a calor (Enfermedad)'),
    ('Ergonómicos', 'Energía', 'Térmica', 'Relaciones dimensionales (antropometría)', 'Relaciones dimensionales ubicación movimientos necesarios para realizar el trabajo por  distancias, alturas.', 'Exposición a relaciones dimensionales (Sobre esfuerzo, golpe)'),
    ('Ergonómicos', 'Energía', 'Térmica', 'Distribución o congestión', 'Distribución (distribución inadecuada de materiales o equipos para realizar el trabajo, lo que motiva movimientos y esfuerzos innecesarios) o congestión (excesiva cantidad  de materiales o equipos innecesarios en el área de trabajo)', 'Exposición a distribución inadecuada (Sobre esfuerzo, golpe)'),
    ('Ergonómicos', 'Materia', 'N.A.', 'Manejo manual de cargas', 'Manejo manual de Cargas (provoca fatiga por factores como peso de los materiales, frecuencia de movimientos distancias y posiciones inadecuadas para el manejo manual de materiales)', 'Exposición a manejo manual de cargas (Sobre esfuerzo, golpe)'),
    ('Ergonómicos', 'Materia', 'N.A.', 'Operaciones mentales', '', ''),
    ('Ergonómicos', 'Materia', 'N.A.', 'Nivel de atención', 'Nivel de atención Visual (actividades de inspección de materiales o de precisión que aun con condiciones adecuadas de iluminación provocan fatiga visual)', ''),
    ('Ergonómicos', 'Materia', 'N.A.', 'Movimientos repetitivos', 'Movimientos repetitivos (se sobre carga alguna extremidad del cuerpo)', 'Exposición amovimientos repetitivos (Sobre esfuerzo)'),
    ('Ergonómicos', 'Materia', 'N.A.', 'Posturas', 'Posturas  (provocan fatiga o sobreesfuerzo de alguna parte de nuestro sistema musculoesqueletico)', 'Exposición a postura (Sobre esfuerzo)'),
    ('Psicosociales', 'NA', 'NA', 'Desarrollo personal', 'Entrenamiento, reconocimiento', ''),
    ('Psicosociales', 'NA', 'NA', 'Carga de trabajo', 'Cargas y ritmos de trabajo excesivos, horarios excesivamente prolongados', ''),
    ('Psicosociales', 'NA', 'NA', 'Contenido del trabajo y rol', 'Funciones y responsabilidades no definidas para el rol', ''),
    ('Psicosociales', 'NA', 'NA', 'Participación y sensación de control', 'Influencia sobre la forma en que se realiza el trabajo, Participación en Manejo del cambio, sentido de pertenencia.', ''),
    ('Psicosociales', 'NA', 'NA', 'Cultura y relaciones personales', 'Discriminación, exclusión, hostigamiento, mobbing, violencia', ''),
    ('', '', '', '', 'Uso de Herramienta Automatica; propulsado por  por cualquier tipo de energia, (taladros, etc.)', 'Golpeado por energias  (heridas, contusiones, Fracturas, Amputaciones)'),
    ('', '', '', '', 'Uso de Herramienta Manual;  martillos, llaves, destornilladores, etc.', 'Golpeado por herramienta (Golpes contusos, Fracturas)'),
    ('', '', '', '', 'Superficies de Trabajo,  filosas, ásperas. (Áreas de equipos, maquinaria, edificios)', 'Contacto con superficies filosas, ásperas (Heridas cortantes)'),
]
