# Generated by Django 5.2.17 on 2026-08-29 01:07

import camaras_ia.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("ip", models.GenericIPAddressField(verbose_name="dirección IP")),
                (
                    "puerto_onvif",
                    models.PositiveIntegerField(
                        default=80, verbose_name="puerto ONVIF"
                    ),
                ),
                (
                    "usuario_onvif",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="usuario ONVIF"
                    ),
                ),
                (
                    "password_onvif",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="contraseña ONVIF"
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True,
                        help_text="Descripción del punto donde está instalada",
                        max_length=255,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="camaras",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "cámara",
                "verbose_name_plural": "cámaras",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="EquipoLocal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "api_key",
                    models.CharField(
                        default=camaras_ia.models.generar_api_key,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("ultima_conexion", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipos_locales",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "equipo local",
                "verbose_name_plural": "equipos locales",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ZonaRestringida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "poligono",
                    models.JSONField(
                        help_text="Lista de coordenadas [[x1, y1], [x2, y2], ...] sobre el encuadre de referencia",
                        verbose_name="polígono",
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "camara",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zonas",
                        to="camaras_ia.camara",
                    ),
                ),
            ],
            options={
                "verbose_name": "zona restringida",
                "verbose_name_plural": "zonas restringidas",
                "ordering": ["camara", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ReglaAlerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=150)),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                (
                    "dias_semana",
                    models.JSONField(
                        default=list,
                        help_text="Lista de días activos, 0=Lunes ... 6=Domingo",
                        verbose_name="días de la semana",
                    ),
                ),
                (
                    "canal_notificacion",
                    models.CharField(
                        choices=[("whatsapp", "WhatsApp"), ("correo", "Correo")],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                (
                    "destinatario",
                    models.CharField(
                        help_text="Número de WhatsApp o correo del destinatario",
                        max_length=150,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "zona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas",
                        to="camaras_ia.zonarestringida",
                    ),
                ),
            ],
            options={
                "verbose_name": "regla de alerta",
                "verbose_name_plural": "reglas de alerta",
                "ordering": ["zona", "hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="EventoDetectado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=camaras_ia.models.snapshot_upload_to,
                    ),
                ),
                ("disparo_alerta", models.BooleanField(default=False)),
                (
                    "estado",
                    models.CharField(
                        choices=[("nuevo", "Nuevo"), ("revisado", "Revisado")],
                        default="nuevo",
                        max_length=20,
                    ),
                ),
                (
                    "camara",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="camaras_ia.camara",
                    ),
                ),
                (
                    "zona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos",
                        to="camaras_ia.zonarestringida",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento detectado",
                "verbose_name_plural": "eventos detectados",
                "ordering": ["-timestamp"],
            },
        ),
    ]
