# Generated by Django 5.2.17 on 2026-08-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camaras_ia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="camara",
            name="snapshot_referencia",
            field=models.ImageField(
                blank=True,
                help_text="Encuadre fijo de la cámara sobre el que se dibujan las zonas restringidas",
                null=True,
                upload_to="camaras/referencia",
                verbose_name="snapshot de referencia",
            ),
        ),
        migrations.AddField(
            model_name="eventodetectado",
            name="punto_x",
            field=models.FloatField(
                blank=True,
                help_text="Coordenada del punto reportado por el equipo local, mismo sistema que el polígono de la zona",
                null=True,
                verbose_name="punto detectado (x)",
            ),
        ),
        migrations.AddField(
            model_name="eventodetectado",
            name="punto_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="punto detectado (y)"
            ),
        ),
    ]
