# Generated by Django 5.2.17 on 2026-08-31 02:15

import camaras_ia.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "camaras_ia",
            "0002_camara_snapshot_referencia_eventodetectado_punto_x_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="camara",
            name="snapshot_referencia",
            field=models.ImageField(
                blank=True,
                help_text="Encuadre fijo de la cámara sobre el que se dibujan las zonas restringidas",
                null=True,
                upload_to="camaras/referencia",
                validators=[core.validators.validar_tamano_archivo],
                verbose_name="snapshot de referencia",
            ),
        ),
        migrations.AlterField(
            model_name="eventodetectado",
            name="snapshot",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=camaras_ia.models.snapshot_upload_to,
                validators=[core.validators.validar_tamano_archivo],
            ),
        ),
    ]
