# Generated by Django 5.2.17 on 2026-08-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camaras_ia", "0003_alter_camara_snapshot_referencia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventodetectado",
            name="notificacion_detalle",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="detalle de la notificación"
            ),
        ),
        migrations.AddField(
            model_name="eventodetectado",
            name="notificacion_enviada",
            field=models.BooleanField(
                default=False,
                help_text="True si disparar_alerta logró enviar la notificación (hoy solo canal correo, vía Brevo)",
                verbose_name="notificación enviada",
            ),
        ),
    ]
