# Generated by Django 5.2.17 on 2026-08-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camaras_ia", "0004_eventodetectado_notificacion_detalle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camara",
            name="rtsp_url",
            field=models.CharField(
                blank=True,
                help_text="URL completa del stream RTSP (con usuario/contraseña si aplica). Si se deja vacío, el equipo local usa el patrón estándar de Dahua con la IP y las credenciales ONVIF de arriba — ver Camara.rtsp_url_efectiva.",
                max_length=500,
                verbose_name="URL RTSP",
            ),
        ),
    ]
