# Generated by Django 5.2.17 on 2026-08-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camaras_ia", "0005_camara_rtsp_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventodetectado",
            name="canal_notificacion",
            field=models.CharField(
                blank=True,
                choices=[("whatsapp", "WhatsApp"), ("correo", "Correo")],
                help_text="Canal de la regla que disparó la alerta — vacío si no hubo disparo_alerta",
                max_length=20,
                verbose_name="canal de notificación",
            ),
        ),
    ]
