# Generated by Django 5.2.17 on 2026-08-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camaras_ia", "0006_eventodetectado_canal_notificacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionNotificaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brevo_api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Brevo API key"
                    ),
                ),
                (
                    "brevo_remitente_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo remitente"
                    ),
                ),
                (
                    "brevo_remitente_nombre",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="nombre remitente"
                    ),
                ),
                (
                    "actualizada_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizada en"),
                ),
            ],
            options={
                "verbose_name": "configuración de notificaciones",
                "verbose_name_plural": "configuración de notificaciones",
            },
        ),
    ]
