# Generated by Django 5.2.17 on 2026-09-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camaras_ia", "0007_configuracionnotificaciones"),
    ]

    operations = [
        migrations.AddField(
            model_name="camara",
            name="calibracion_distancia_metros",
            field=models.FloatField(
                blank=True,
                help_text="Distancia real, en metros, entre los dos puntos de calibración marcados sobre el snapshot",
                null=True,
                verbose_name="calibración: distancia real (m)",
            ),
        ),
        migrations.AddField(
            model_name="camara",
            name="calibracion_punto1_x",
            field=models.FloatField(
                blank=True, null=True, verbose_name="calibración: punto 1 (x)"
            ),
        ),
        migrations.AddField(
            model_name="camara",
            name="calibracion_punto1_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="calibración: punto 1 (y)"
            ),
        ),
        migrations.AddField(
            model_name="camara",
            name="calibracion_punto2_x",
            field=models.FloatField(
                blank=True, null=True, verbose_name="calibración: punto 2 (x)"
            ),
        ),
        migrations.AddField(
            model_name="camara",
            name="calibracion_punto2_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="calibración: punto 2 (y)"
            ),
        ),
        migrations.AddField(
            model_name="zonarestringida",
            name="centro_x",
            field=models.FloatField(
                blank=True,
                help_text="Punto marcado (ej. una estiba) sobre el encuadre de referencia — solo para tipo Punto y radio",
                null=True,
                verbose_name="centro (x)",
            ),
        ),
        migrations.AddField(
            model_name="zonarestringida",
            name="centro_y",
            field=models.FloatField(blank=True, null=True, verbose_name="centro (y)"),
        ),
        migrations.AddField(
            model_name="zonarestringida",
            name="radio_metros",
            field=models.FloatField(
                blank=True,
                help_text="Distancia real, en metros, alrededor del centro que se considera zona restringida — solo para tipo Punto y radio",
                null=True,
                verbose_name="radio (metros)",
            ),
        ),
        migrations.AddField(
            model_name="zonarestringida",
            name="tipo",
            field=models.CharField(
                choices=[("poligono", "Polígono"), ("punto_radio", "Punto y radio")],
                default="poligono",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="zonarestringida",
            name="poligono",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de coordenadas [[x1, y1], [x2, y2], ...] sobre el encuadre de referencia — solo para tipo Polígono",
                verbose_name="polígono",
            ),
        ),
    ]
