# Generated by Django 5.2.17 on 2026-09-09 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camaras_ia", "0008_camara_calibracion_distancia_metros_and_more"),
        ("core", "0005_registroiniciosesion"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstruccionSeguridad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField(verbose_name="instrucción")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de revisar"),
                            ("configurada", "Ya configurada como zona"),
                            ("requiere_desarrollo", "Necesita desarrollo aparte"),
                        ],
                        default="pendiente",
                        max_length=30,
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        help_text="Para el equipo técnico: qué hace falta para automatizarla.",
                        verbose_name="notas internas",
                    ),
                ),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("actualizada_en", models.DateTimeField(auto_now=True)),
                (
                    "camara",
                    models.ForeignKey(
                        blank=True,
                        help_text="Opcional — se puede escribir la instrucción antes de saber a qué cámara aplica.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrucciones",
                        to="camaras_ia.camara",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrucciones_seguridad",
                        to="core.empresa",
                    ),
                ),
                (
                    "zona",
                    models.ForeignKey(
                        blank=True,
                        help_text="Se enlaza acá una vez que la instrucción ya quedó configurada como zona real.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instrucciones",
                        to="camaras_ia.zonarestringida",
                    ),
                ),
            ],
            options={
                "verbose_name": "instrucción de seguridad",
                "verbose_name_plural": "instrucciones de seguridad",
                "ordering": ["-creada_en"],
            },
        ),
    ]
