# Generated by Django 5.2.17 on 2026-09-12 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camaras_ia", "0009_instruccionseguridad"),
        ("core", "0005_registroiniciosesion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proveedor",
                    models.CharField(
                        choices=[
                            ("claude", "Claude (Anthropic)"),
                            ("gemini", "Gemini (Google)"),
                        ],
                        default="claude",
                        max_length=20,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API key"
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        blank=True,
                        help_text="ID del modelo a usar, ej. claude-opus-5 o gemini-flash-latest. Vacío = valor por defecto según el proveedor (ver ia_deteccion.MODELOS_POR_DEFECTO).",
                        max_length=100,
                        verbose_name="modelo",
                    ),
                ),
                (
                    "actualizada_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizada en"),
                ),
            ],
            options={
                "verbose_name": "configuración de IA",
                "verbose_name_plural": "configuración de IA",
            },
        ),
        migrations.AddField(
            model_name="eventodetectado",
            name="descripcion_ia",
            field=models.TextField(blank=True, verbose_name="descripción de la IA"),
        ),
        migrations.AddField(
            model_name="eventodetectado",
            name="ia_analizado_en",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="analizado por IA en"
            ),
        ),
        migrations.AddField(
            model_name="eventodetectado",
            name="ia_error",
            field=models.CharField(
                blank=True,
                help_text="Si la clasificación falló (API caída, sin créditos, etc.) — el evento sigue su curso normal igual.",
                max_length=255,
                verbose_name="error de análisis IA",
            ),
        ),
        migrations.CreateModel(
            name="TipoEventoIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Qué debe buscar la IA en la imagen — en lenguaje natural, con el mayor detalle posible."
                    ),
                ),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos_evento_ia",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo de evento IA",
                "verbose_name_plural": "tipos de evento IA",
                "ordering": ["empresa", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="eventodetectado",
            name="tipos_ia",
            field=models.ManyToManyField(
                blank=True,
                help_text="Cuáles del catálogo de TipoEventoIA identificó la IA en este snapshot.",
                related_name="eventos",
                to="camaras_ia.tipoeventoia",
                verbose_name="eventos detectados por IA",
            ),
        ),
    ]
