# Generated by Django 5.2.17 on 2026-09-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camaras_ia", "0010_configuracionia_eventodetectado_descripcion_ia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipolocal",
            name="visor_password",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="contraseña del visor web"
            ),
        ),
        migrations.AddField(
            model_name="equipolocal",
            name="visor_usuario",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="usuario del visor web"
            ),
        ),
    ]
