# Generated by Django 5.2.17 on 2026-10-06 19:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camaras_ia", "0011_equipolocal_visor_password_equipolocal_visor_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionia",
            name="consumo_desde",
            field=models.DateTimeField(
                blank=True,
                help_text="Inicio del periodo que se compara contra el tope — se reinicia al recargar créditos. Vacío = desde siempre.",
                null=True,
                verbose_name="contar consumo desde",
            ),
        ),
        migrations.AddField(
            model_name="configuracionia",
            name="tope_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("20.00"),
                help_text="Al llegar a este gasto estimado (desde consumo_desde) se dejan de hacer llamadas a Claude.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="tope de consumo (USD)",
            ),
        ),
        migrations.CreateModel(
            name="ConsumoIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modelo", models.CharField(max_length=100)),
                ("tokens_entrada", models.PositiveIntegerField(default=0)),
                ("tokens_salida", models.PositiveIntegerField(default=0)),
                ("tokens_cache_escritura", models.PositiveIntegerField(default=0)),
                ("tokens_cache_lectura", models.PositiveIntegerField(default=0)),
                (
                    "costo_usd",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=12,
                        verbose_name="costo estimado (USD)",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consumos_ia",
                        to="camaras_ia.eventodetectado",
                    ),
                ),
            ],
            options={
                "verbose_name": "consumo de IA",
                "verbose_name_plural": "consumo de IA",
                "ordering": ["-creado_en"],
            },
        ),
    ]
