# Generated by Django 5.2.17 on 2026-10-06 19:41

from django.db import migrations, models


def asignar_a_todas_las_camaras_de_su_empresa(apps, schema_editor):
    """Antes cada tipo aplicaba a todas las cámaras de su empresa: se deja
    así asignado para que nada cambie al desplegar, hasta reasignarlo."""
    TipoEventoIA = apps.get_model("camaras_ia", "TipoEventoIA")
    Camara = apps.get_model("camaras_ia", "Camara")
    for tipo in TipoEventoIA.objects.all():
        tipo.camaras.set(Camara.objects.filter(empresa_id=tipo.empresa_id))


class Migration(migrations.Migration):

    dependencies = [
        ("camaras_ia", "0012_consumo_ia"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipoeventoia",
            name="camaras",
            field=models.ManyToManyField(
                blank=True,
                help_text="Cámaras en las que la IA revisa este evento. Sin cámaras no se revisa en ninguna.",
                related_name="tipos_evento_ia",
                to="camaras_ia.camara",
                verbose_name="cámaras",
            ),
        ),
        migrations.RunPython(asignar_a_todas_las_camaras_de_su_empresa, migrations.RunPython.noop),
    ]
