# Generated by Django 5.2.17 on 2026-10-06 19:48

import django.db.models.deletion
from django.db import migrations, models


def camara_desde_el_evento(apps, schema_editor):
    ConsumoIA = apps.get_model("camaras_ia", "ConsumoIA")
    for consumo in ConsumoIA.objects.filter(evento__isnull=False).select_related("evento"):
        consumo.camara_id = consumo.evento.camara_id
        consumo.save(update_fields=["camara"])


class Migration(migrations.Migration):

    dependencies = [
        ("camaras_ia", "0013_tipos_evento_ia_por_camara"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumoia",
            name="camara",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consumos_ia",
                to="camaras_ia.camara",
            ),
        ),
        migrations.RunPython(camara_desde_el_evento, migrations.RunPython.noop),
    ]
